### ISSUE TITLE
Not working on read-only src trees

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [behdad/git.mk#38]
This is not working when building out of tree with a read-only src directory. See
https://github.com/tpm2-software/tpm2-tss/issues/2271

So we are considering git.mk to not be part of `all:` if git.mk could just skip generation if it fails.

**Comment by behdad** [comment]
Ignoring failure if it's readonly when called from `all` sounds good to me, if we can pull that off.

**Comment by AndreasFuchsSIT** [comment]
How about
```
diff --git a/git.mk b/git.mk
index 6874a32f..a87084bd 100644
--- a/git.mk
+++ b/git.mk
@@ -380,7 +380,7 @@ $(srcdir)/.gitignore: Makefile.am $(top_srcdir)/git.mk $(top_srcdir)/configure.a
        sed "s@^/`echo "$(srcdir)" | sed 's/\(.\)/[\1]/g'`/@/@" | \
        sed 's@/[.]/@/@g' | \
        LC_ALL=C sort | uniq > $@.tmp && \
-       mv $@.tmp $@;
+       mv -f $@.tmp $@ || echo "WARNING: Cannot create .gitignore file; skipping";
 
 all: $(srcdir)/.gitignore gitignore-recurse-maybe
 gitignore: $(srcdir)/.gitignore gitignore-recurse
```

**Comment by behdad** [comment]
Wouldn't the tmp file be unwriteable as well?

**Comment by behdad** [comment]
If the src directory is unwritable?

**Comment by AndreasFuchsSIT** [comment]
Yes. but the `||` catches this as well...

**Comment by behdad** [comment]
Right...

**Comment by behdad** [comment]
This will leave .gitignore files stale if the generation fails for any reason though. That makes me a bit uneasy.

What I prefer is that we try to generate the tmp file in the build directory, and only if the move to the final destination failed we ignore that.

**Comment by AndreasFuchsSIT** [comment]
Fine with me

**Comment by behdad** [comment]
Let me try.

**Comment by behdad** [comment]
Please test https://github.com/behdad/git.mk/pull/39

**Comment by AndreasFuchsTPM** [comment]
Thanks
